apiServer:
  port: 8080
  publicHost: podfly-render-api-pg.onrender.com
  publicPort: 443
  publicScheme: https

database:
  host: dpg-d9f7863rjlhs73dmilqg-a.oregon-postgres.render.com
  port: 5432
  name: podfly_render_api_pg_db
  user: podfly_render_api_pg_db_user
  requireSsl: true

sessionLogs:
  consoleEnabled: true
  persistentEnabled: false
